platform: Sumo Logic
source: windows_security
description: Text that describe current mapping

log_source:
  _sourceCategory: [windows]
  _sourceName: Security

default_log_source:
  _sourceCategory: windows
  _sourceName: Security

field_mapping:
  EventID: EventID
  ParentImage: ParentProcessName
  AccessMask: AccessMask
  AccountName: AccountName
  AllowedToDelegateTo: AllowedToDelegateTo
  AttributeLDAPDisplayName: AttributeLDAPDisplayName
  AuditPolicyChanges: AuditPolicyChanges
  AuthenticationPackageName: AuthenticationPackageName
  Channel: _sourceName
  ComputerName: WorkstationName
  FailureReason: FailureReason
  IpAddress: IpAddress
  IpPort: IpPort
  KeyLength: KeyLength
  LogonProcessName: LogonProcessName
  LogonType: LogonType
  MemberName: MemberName
  MemberSid: MemberSid
  NewProcessName: NewProcessName
  ObjectClass: ObjectClass
  ObjectName: ObjectName
  ObjectType: ObjectType
  CommandLine: CommandLine
  OldUacValue: OldUacValue
  CertIssuerName: CertIssuerName
  SubStatus: SubStatus
  DisplayName: DisplayName
  ServiceSid: ServiceSid
  CertThumbprint: CertThumbprint
  NewSd: NewSd
  TestSigning: TestSigning
  TargetInfo: TargetInfo
  ServiceAccount: ServiceAccount
  ClientProcessId: ClientProcessId
  AttributeValue: AttributeValue
  SessionName: SessionName
  TaskName: TaskName
  ObjectDN: ObjectDN
  SourcePort: SourcePort
  PasswordLastSet: PasswordLastSet
  PrivilegeList: PrivilegeList
  TargetServerName: TargetServerName
  OperationType: OperationType
  DestPort: DestPort
  ServiceStartType: ServiceStartType
  UserPrincipalName: UserPrincipalName
  DnsHostName: DnsHostName
  AuditSourceName: AuditSourceName
  Workstation: Workstation
  DestAddress: DestAddress
  PreAuthType: PreAuthType
  SecurityPackageName: PackageName
  SubjectLogonId: SubjectLogonId
  NewUacValue: NewUacValue
  EnabledPrivilegeList: EnabledPrivilegeList
  RelativeTargetName: ObjectType
  CertSerialNumber: CertSerialNumber
  SidHistory: SidHistory
  TargetLogonId: TargetLogonId
  KernelDebug: KernelDebug
  CallerProcessName: CallerProcessName
  ProcessName: ProcessName
  Properties: Properties
  UserAccountControl: UserAccountControl
  ServiceFileName: ServiceFileName
  SecurityDescriptor: SecurityDescriptor
  ServiceName: ServiceName
  ShareName: ShareName
  Status: Status
  SubjectDomainName: SubjectDomainName
  SubjectUserName: SubjectUserName
  SubjectUserSid: SubjectUserSid
  SourceAddr: SourceAddr
  SourceAddress: SourceAddress
  TargetName: TargetName
  ServicePrincipalNames: ServicePrincipalNames
  TargetDomainName: TargetDomainName
  TargetSid: TargetSid
  TargetUserName: TargetUserName
  ObjectServer: ObjectServer
  TargetUserSid: TargetUserSid
  TicketEncryptionType: TicketEncryptionType
  TicketOptions: TicketOptions
  WorkstationName: WorkstationName
  TransmittedServices: TransmittedServices
  LayerRTID: LayerRTID
  BSSID: SSID
  BSSType: BSSType
  CipherAlgorithm: Cipher
  ConnectionId: ConnectionId
  InterfaceDescription: Adapter
  InterfaceGuid: DeviceGuid
  OnexEnabled: OnexEnabled
  SSID: SSID
  ServiceType: ServiceType
  ParentProcessName: ParentProcessName
