platform: Global OCSF
source: default

default_log_source: {}

fieldmappings:
  IntegrityLevel: process.integrity
  ParentCommandLine:
    - process.parent_process.cmd_line
    - actor.process.cmd_line
  ParentUser: process.parent_process.user
  Product:
    - process.file.product.name
    - process.file.product.vendor_name
  TargetFilename: file.name
  OriginalFileName: module.file.path
  TargetObject:
    - reg_key.path
    - reg_value.name
    - reg_value.path
  AdditionalEventData: unmapped.additionalEventData
  additionalEventData.MFAUsed: unmapped.additionalEventData.MFAUsed
  eventType: unmapped.eventType
  responseElements: unmapped.responseElements
  responseElements.ConsoleLogin: unmapped.responseElements.ConsoleLogin
  userAgent: http_request.user_agent
  userIdentity.arn: unmapped.userIdentity_sessionContext_sessionIssuer_arn
  userIdentity.principalId: unmapped.userIdentity_sessionContext_sessionIssuer_principalId
  userIdentity.sessionContext.sessionIssuer.type: unmapped.userIdentity_sessionContext_sessionIssuer_type
  userIdentity.type: identity.user.type
  userIdentity.userName: unmapped.userIdentity_sessionContext_sessionIssuer_userName
  a0: unmapped.a0
  a1: unmapped.a1
  a2: unmapped.a2
  a3: unmapped.a3
  AADOperationType: unmapped.AADOperationType
  Accesses: unmapped.Accesses
  AccessMask: unmapped.AccessMask
  AccountName: unmapped.AccountName
  action: unmapped.action
  action_id: unmapped.action_id
  ActionType: unmapped.ActionType
  ActivityDisplayName: unmapped.ActivityDisplayName
  ActivityInsights: unmapped.ActivityInsights
  ActivityStatus: unmapped.ActivityStatus
  ActivityStatusValue: unmapped.ActivityStatusValue
  ActivitySubstatusValue: unmapped.ActivitySubstatusValue
  ActivityType: unmapped.ActivityType
  additional_information: unmapped.additional_information
  Address: unmapped.Address
  AllowedToDelegateTo: unmapped.AllowedToDelegateTo
  alternateId: unmapped.alternateId
  answers: unmapped.answers
  AppDisplayName: unmapped.AppDisplayName
  AppId: unmapped.AppId
  ApplicationPath: unmapped.ApplicationPath
  attackName: unmapped.attackName
  AttributeLDAPDisplayName: unmapped.AttributeLDAPDisplayName
  AttributeValue: unmapped.AttributeValue
  AuditPolicyChanges: unmapped.AuditPolicyChanges
  AuditSourceName: unmapped.AuditSourceName
  AuthenticationAlgorithm: unmapped.AuthenticationAlgorithm
  AuthenticationPackageName: unmapped.AuthenticationPackageName
  AuthenticationRequirement: unmapped.AuthenticationRequirement
  AuthenticationType: unmapped.AuthenticationType
  Authorization: unmapped.Authorization
  aws_node_type: unmapped.aws_node_type
  backupConfiguration.enabled: unmapped.backupConfiguration.enabled
  BSSID: unmapped.BSSID
  BSSType: unmapped.BSSType
  c-uri: unmapped.c-uri
  c-uri-extension: unmapped.c-uri-extension
  c-uri-query: unmapped.c-uri-query
  c-useragent: unmapped.c-useragent
  CallerIpAddress: unmapped.CallerIpAddress
  CallerProcessName: unmapped.CallerProcessName
  CallingProcessName: unmapped.CallingProcessName
  CallTrace: unmapped.CallTrace
  Caption: unmapped.Caption
  category: unmapped.category
  CategoryValue: unmapped.CategoryValue
  certificate.serial: unmapped.certificate.serial
  CertIssuerName: unmapped.CertIssuerName
  CertSerialNumber: unmapped.CertSerialNumber
  CertThumbprint: unmapped.CertThumbprint
  Channel: unmapped.Channel
  cipher: unmapped.cipher
  CipherAlgorithm: unmapped.CipherAlgorithm
  class_type: unmapped.class_type
  ClassName: unmapped.ClassName
  client: unmapped.client
  client_header_names: unmapped.client_header_names
  client.as.number: unmapped.client.as.number
  client.as.organization.name: unmapped.client.as.organization.name
  client.device: unmapped.client.device
  client.domain: unmapped.client.domain
  client.id: unmapped.client.id
  client.ip: unmapped.client.ip
  client.user.full_name: unmapped.client.user.full_name
  client.user.id: unmapped.client.user.id
  client.zone: unmapped.client.zone
  ClientInfoString: unmapped.ClientInfoString
  ClientProcessId: unmapped.ClientProcessId
  CommandLine: unmapped.CommandLine
  ComplianceState: unmapped.ComplianceState
  ComputerName: unmapped.ComputerName
  ConditionalAccessStatus: unmapped.ConditionalAccessStatus
  conn_state: unmapped.conn_state
  ConnectionId: unmapped.ConnectionId
  ConnectionMode: unmapped.ConnectionMode
  CONSUMER: unmapped.CONSUMER
  cookie: unmapped.cookie
  cs-bytes: unmapped.cs-bytes
  cs-cookie: unmapped.cs-cookie
  cs-cookie-vars: unmapped.cs-cookie-vars
  cs-host: unmapped.cs-host
  cs-method: unmapped.cs-method
  cs-referrer: unmapped.cs-referrer
  cs-version: unmapped.cs-version
  CurrentDirectory: unmapped.CurrentDirectory
  Data: unmapped.Data
  data.protoPayload.methodName: unmapped.data.protoPayload.methodName
  data.protoPayload.request.function.timeout: unmapped.data.protoPayload.request.function.timeout
  data.protoPayload.serviceData.policyDelta.bindingDeltas{}.action: unmapped.data.protoPayload.serviceData.policyDelta.bindingDeltas{}.action
  data.protoPayload.serviceData.policyDelta.bindingDeltas{}.member: unmapped.data.protoPayload.serviceData.policyDelta.bindingDeltas{}.member
  data.resource.type: unmapped.data.resource.type
  Description: unmapped.Description
  desktop_height: unmapped.desktop_height
  desktop_width: unmapped.desktop_width
  DestAddress: unmapped.DestAddress
  Destination: unmapped.Destination
  DestinationHostname: unmapped.DestinationHostname
  DestinationIp: unmapped.DestinationIp
  DestinationPort: unmapped.DestinationPort
  DestPort: unmapped.DestPort
  Details: unmapped.Details
  Device: unmapped.Device
  DeviceDescription: unmapped.DeviceDescription
  DeviceDetail: unmapped.DeviceDetail
  DeviceName: unmapped.DeviceName
  DevicesInsights: unmapped.DevicesInsights
  DisableIntegrityChecks: unmapped.DisableIntegrityChecks
  DisplayName: unmapped.DisplayName
  dns-answer: unmapped.dns-answer
  dns-query: unmapped.dns-query
  dns-record: unmapped.dns-record
  DnsHostName: unmapped.DnsHostName
  Domain: unmapped.Domain
  dst_ip: unmapped.dst_ip
  dst_port: unmapped.dst_port
  dst-ip: unmapped.dst-ip
  dst-port: unmapped.dst-port
  EnabledPrivilegeList: unmapped.EnabledPrivilegeList
  endpoint: unmapped.endpoint
  errorCode: unmapped.errorCode
  errorMessage: unmapped.errorMessage
  event.action: unmapped.event.action
  event.outcome: unmapped.event.outcome
  EventData: unmapped.EventData
  EventID: unmapped.EventID
  eventName: unmapped.eventName
  eventSource: unmapped.eventSource
  EventType: unmapped.EventType
  exe: unmapped.exe
  FailureReason: unmapped.FailureReason
  Faultingapplicationpath: unmapped.Faultingapplicationpath
  fc_request: unmapped.fc_request
  FileName: unmapped.FileName
  filetype: unmapped.filetype
  function: unmapped.function
  gcp.audit.method_name: unmapped.gcp.audit.method_name
  GrantedAccess: unmapped.GrantedAccess
  has_cert_table: unmapped.has_cert_table
  Hashes: unmapped.Hashes
  history: unmapped.history
  HiveName: unmapped.HiveName
  host: unmapped.host
  Hostname: unmapped.Hostname
  http.bodyMagic: unmapped.http.bodyMagic
  http.method: unmapped.http.method
  id_resp_p: unmapped.id_resp_p
  id.orig_h: unmapped.id.orig_h
  id.orig_p: unmapped.id.orig_p
  id.resp_h: unmapped.id.resp_h
  id.resp_p: unmapped.id.resp_p
  Image: unmapped.Image
  ImageLoaded: unmapped.ImageLoaded
  ImageName: unmapped.ImageName
  ImagePath: unmapped.ImagePath
  inference: unmapped.inference
  Initiated: unmapped.Initiated
  InitiatedBy: unmapped.InitiatedBy
  InterfaceDescription: unmapped.InterfaceDescription
  InterfaceGuid: unmapped.InterfaceGuid
  IpAddress: unmapped.IpAddress
  IpPort: unmapped.IpPort
  IsInteractive: unmapped.IsInteractive
  Issuer: unmapped.Issuer
  jsonPayload.enforcedSecurityPolicy.configuredAction: unmapped.jsonPayload.enforcedSecurityPolicy.configuredAction
  jsonPayload.enforcedSecurityPolicy.matchedFieldValue: unmapped.jsonPayload.enforcedSecurityPolicy.matchedFieldValue
  KernelDebug: unmapped.KernelDebug
  keyboard_layout: unmapped.keyboard_layout
  KeyLength: unmapped.KeyLength
  LayerRTID: unmapped.LayerRTID
  Level: unmapped.Level
  LinkName: unmapped.LinkName
  local_orig: unmapped.local_orig
  local_resp: unmapped.local_resp
  LocalName: unmapped.LocalName
  LogEntry: unmapped.LogEntry
  logged_ssh_inference: unmapped.logged_ssh_inference
  LoggedByService: unmapped.LoggedByService
  LogonError: unmapped.LogonError
  LogonProcessName: unmapped.LogonProcessName
  LogonType: unmapped.LogonType
  MemberName: unmapped.MemberName
  MemberSid: unmapped.MemberSid
  message: unmapped.message
  method: unmapped.method
  methodName: unmapped.methodName
  mime_type: unmapped.mime_type
  mime_types: unmapped.mime_types
  ModifiedProperties: unmapped.ModifiedProperties
  ModifyingApplication: unmapped.ModifyingApplication
  name: unmapped.name
  Namespace: unmapped.Namespace
  NetworkLocationDetails: unmapped.NetworkLocationDetails
  NewProcessName: unmapped.NewProcessName
  NewSd: unmapped.NewSd
  NewTargetUserName: unmapped.NewTargetUserName
  NewTemplateContent: unmapped.NewTemplateContent
  NewUacValue: unmapped.NewUacValue
  NewValue: unmapped.NewValue
  note: unmapped.note
  notice.cipher: unmapped.notice.cipher
  notice.password: unmapped.notice.password
  notice.request_type: unmapped.notice.request_type
  notice.user_agent: unmapped.notice.user_agent
  NotificationPackageName: unmapped.NotificationPackageName
  object_name: unmapped.object_name
  ObjectClass: unmapped.ObjectClass
  ObjectDN: unmapped.ObjectDN
  ObjectName: unmapped.ObjectName
  objectRef.namespace: unmapped.objectRef.namespace
  objectRef.resource: unmapped.objectRef.resource
  objectRef.subresource: unmapped.objectRef.subresource
  ObjectServer: unmapped.ObjectServer
  ObjectType: unmapped.ObjectType
  ObjectValueName: unmapped.ObjectValueName
  OfficeObjectId: unmapped.OfficeObjectId
  OfficeWorkload: unmapped.OfficeWorkload
  OldTargetUserName: unmapped.OldTargetUserName
  OldUacValue: unmapped.OldUacValue
  OldValue: unmapped.OldValue
  OnexEnabled: unmapped.OnexEnabled
  operation: unmapped.operation
  OperationName: unmapped.OperationName
  OperationNameValue: unmapped.OperationNameValue
  OperationType: unmapped.OperationType
  orig_bytes: unmapped.orig_bytes
  Origin: unmapped.Origin
  outcome.reason: unmapped.outcome.reason
  param1: unmapped.param1
  param2: unmapped.param2
  Parameters: unmapped.Parameters
  parent-domain: unmapped.parent-domain
  ParentImage: unmapped.ParentImage
  ParentProcessName: unmapped.ParentProcessName
  PasswordLastSet: unmapped.PasswordLastSet
  path: unmapped.path
  PHYType: unmapped.PHYType
  PipeName: unmapped.PipeName
  PossibleCause: unmapped.PossibleCause
  post-body: unmapped.post-body
  PreAuthType: unmapped.PreAuthType
  PreviousCreationUtcTime: unmapped.PreviousCreationUtcTime
  PrivilegeList: unmapped.PrivilegeList
  Process_Name: unmapped.Process_Name
  ProcessName: unmapped.ProcessName
  processPath: unmapped.processPath
  ProfileName: unmapped.ProfileName
  Properties: unmapped.Properties
  properties.message: unmapped.properties.message
  proto: unmapped.proto
  protoPayload.methodName: unmapped.protoPayload.methodName
  protoPayload.request.canIpForward: unmapped.protoPayload.request.canIpForward
  protoPayload.serviceName: unmapped.protoPayload.serviceName
  Provider: unmapped.Provider
  Provider_Name: unmapped.Provider_Name
  proxied: unmapped.proxied
  QNAME: unmapped.QNAME
  qtype_name: unmapped.qtype_name
  query: unmapped.query
  QueryName: unmapped.QueryName
  QueryResults: unmapped.QueryResults
  r-dns: unmapped.r-dns
  rcode_name: unmapped.rcode_name
  RecordType: unmapped.RecordType
  referrer: unmapped.referrer
  RegistryValue: unmapped.RegistryValue
  rejected: unmapped.rejected
  related.user: unmapped.related.user
  RelativeTargetName: unmapped.RelativeTargetName
  RemoteName: unmapped.RemoteName
  request_body_len: unmapped.request_body_len
  request_type: unmapped.request_type
  requestObject.rules.resources: unmapped.requestObject.rules.resources
  requestObject.rules.verbs: unmapped.requestObject.rules.verbs
  requestObject.spec.containers.image: unmapped.requestObject.spec.containers.image
  requestParameters: unmapped.requestParameters
  requestParameters.attribute: unmapped.requestParameters.attribute
  requestParameters.ipPermissions.items.ipRanges.items.cidrIP: unmapped.requestParameters.ipPermissions.items.ipRanges.items.cidrIP
  requestParameters.ipPermissions.items.ipRanges.items.fromPort: unmapped.requestParameters.ipPermissions.items.ipRanges.items.fromPort
  requestParameters.userData: unmapped.requestParameters.userData
  requestURI: unmapped.requestURI
  ResourceDisplayName: unmapped.ResourceDisplayName
  ResourceId: unmapped.ResourceId
  ResourceIdentity: unmapped.ResourceIdentity
  ResourceProviderValue: unmapped.ResourceProviderValue
  resp_bytes: unmapped.resp_bytes
  resp_mime_types: unmapped.resp_mime_types
  response_body_len: unmapped.response_body_len
  responseElements.pendingModifiedValues.masterUserPassword: unmapped.responseElements.pendingModifiedValues.masterUserPassword
  responseElements.publiclyAccessible: unmapped.responseElements.publiclyAccessible
  Result: unmapped.Result
  ResultDescription: unmapped.ResultDescription
  ResultReason: unmapped.ResultReason
  ResultStatus: unmapped.ResultStatus
  ResultType: unmapped.ResultType
  RiskDetail: unmapped.RiskDetail
  sc-status: unmapped.sc-status
  SearchFilter: unmapped.SearchFilter
  SecurityDescriptor: unmapped.SecurityDescriptor
  SecurityID: unmapped.SecurityID
  SecurityPackageName: unmapped.SecurityPackageName
  server_name: unmapped.server_name
  ServerName: unmapped.ServerName
  service: unmapped.service
  ServiceAccount: unmapped.ServiceAccount
  ServiceFileName: unmapped.ServiceFileName
  serviceName: unmapped.serviceName
  ServicePrincipalNames: unmapped.ServicePrincipalNames
  ServiceSid: unmapped.ServiceSid
  ServiceStartType: unmapped.ServiceStartType
  ServiceType: unmapped.ServiceType
  SessionName: unmapped.SessionName
  share_name: unmapped.share_name
  ShareName: unmapped.ShareName
  SidHistory: unmapped.SidHistory
  SignatureStatus: unmapped.SignatureStatus
  Signed: unmapped.Signed
  source: unmapped.source
  Source_Name: unmapped.Source_Name
  source.domain: unmapped.source.domain
  source.ip: unmapped.source.ip
  source.user.full_name: unmapped.source.user.full_name
  source.user.id: unmapped.source.user.id
  SourceAddr: unmapped.SourceAddr
  SourceAddress: unmapped.SourceAddress
  SourceFileExtension: unmapped.SourceFileExtension
  SourceFileName: unmapped.SourceFileName
  SourceImage: unmapped.SourceImage
  SourceIp: unmapped.SourceIp
  SourceItemName: unmapped.SourceItemName
  SourceName: unmapped.SourceName
  SourcePort: unmapped.SourcePort
  SourceSystem: unmapped.SourceSystem
  SourceUser: unmapped.SourceUser
  src_ip: unmapped.src_ip
  src_port: unmapped.src_port
  src-ip: unmapped.src-ip
  src-port: unmapped.src-port
  SSID: unmapped.SSID
  stage: unmapped.stage
  StartType: unmapped.StartType
  statement: unmapped.statement
  status: unmapped.status
  status_code: unmapped.status_code
  Status.errorCode: unmapped.Status.errorCode
  Status.failureReason: unmapped.Status.failureReason
  StatusText: unmapped.StatusText
  subject: unmapped.subject
  SubjectDomainName: unmapped.SubjectDomainName
  SubjectLogonId: unmapped.SubjectLogonId
  SubjectUserName: unmapped.SubjectUserName
  SubjectUserSid: unmapped.SubjectUserSid
  SubStatus: unmapped.SubStatus
  subsystem: unmapped.subsystem
  successful: unmapped.successful
  TargetDomainName: unmapped.TargetDomainName
  TargetImage: unmapped.TargetImage
  TargetInfo: unmapped.TargetInfo
  TargetLogonId: unmapped.TargetLogonId
  TargetName: unmapped.TargetName
  TargetResources: unmapped.TargetResources
  TargetServerName: unmapped.TargetServerName
  TargetSid: unmapped.TargetSid
  TargetUser: unmapped.TargetUser
  TargetUserName: unmapped.TargetUserName
  TargetUserSid: unmapped.TargetUserSid
  TaskContent: unmapped.TaskContent
  TaskName: unmapped.TaskName
  TemplateContent: unmapped.TemplateContent
  terminatingRuleId: unmapped.terminatingRuleId
  TestSigning: unmapped.TestSigning
  TicketEncryptionType: unmapped.TicketEncryptionType
  TicketOptions: unmapped.TicketOptions
  till: unmapped.till
  TokenIssuerType: unmapped.TokenIssuerType
  total_bytes: unmapped.total_bytes
  TransmittedServices: unmapped.TransmittedServices
  Type: unmapped.Type
  uri: unmapped.uri
  User: unmapped.User
  user_agent: unmapped.user_agent
  user_agent.original: unmapped.user_agent.original
  user.groups: unmapped.user.groups
  user.username: unmapped.user.username
  UserAccountControl: unmapped.UserAccountControl
  UserAgent: unmapped.UserAgent
  userAgent.browser: unmapped.userAgent.browser
  userAgent.os: unmapped.userAgent.os
  UserContext: unmapped.UserContext
  UserID: unmapped.UserID
  UserName: unmapped.UserName
  UserPrincipalName: unmapped.UserPrincipalName
  UsersInsights: unmapped.UsersInsights
  UsersInsights.IsDormantAccount: unmapped.UsersInsights.IsDormantAccount
  UsersInsights.IsNewAccount: unmapped.UsersInsights.IsNewAccount
  validation_status: unmapped.validation_status
  Value: unmapped.Value
  verb: unmapped.verb
  Workstation: unmapped.Workstation
  WorkstationName: unmapped.WorkstationName
