platform: Qradar
source: default



default_log_source:
  devicetype: 12


field_mapping:
  icmp.type: IcmpType
  icmp.code: IcmpCode
  dst-port:
    - DstPort
    - DestinationPort
    - remoteport
  src-port:
    - SourcePort
    - localport
    - sourcePort
  src-ip:
    - sourceip
    - source_ip
    - SourceIP
    - sourceIP
    - SrcHost
  dst-ip:
    - DestinationIP
    - destinationip
    - destination_ip
    - destinationIP
    - destinationaddress
    - destination
    - DstHost
  User:
    - userName
    - EventUserName
    - Alert Threat Cause Actor Name
    - Username
    - Security ID
  CommandLine: Command
  Protocol:
    - IPProtocol
    - protocol
  Application:
    - Application
    - application
  sourceNetwork: sourceNetwork
  SourceHostName:
    - HostCount-source
    - identityHostName
    - sourceAssetName
    - HostCount-src
  DestinationHostname:
    - HostCount-destination
    - Recipient Host
    - DestinationHostName
    - HostCount-dst
  src-packets:
    - PacketRatio-src
    - src-packets
  dst-packets:
    - PacketRatio-dst
    - dst-packets
  src-bytes: src-bytes
  dst-bytes: dst-bytes
  ExternalSeverity:
    - External Severity
    - Observeit Severity
  SourceMAC:
    - SourceMAC
    - MAC
    - sourceMAC
  DestinationMAC: DestinationMAC
  SourceOS:
    - SourceOS
    - OS
  DestinationOS: DestinationOS
  TargetUserName: DestinationUserName
  SourceUserName: SourceUserName
  url_category: XForceCategoryByURL
  EventSeverity: EventSeverity
  Source:
    - Source
    - source
  duration: duration
  ThreatName:
    - Threat Name
    - Alert Blocked Threat Category
  AnalyzerName: Analyzer Name
  Classification: Classification
  ResultCode: Alert Reason Code
  Technique: Technique
  Action: Action
  Workstation: Machine Identifier
  GroupMembership: Role Name
  FileName: 
    - Filename
    - File Name
    - Encoded Filename
  RegistryKey:
    - Registry Key
    - Target Object
  RegistryValue: RegistryValue
  ProcessPath: Process Path
  hasIdentity: hasIdentity
