platform: Qradar
source: default



default_log_source:
  devicetype: 12


field_mapping:
  icmp.type: IcmpType
  icmp.code: IcmpCode
  dst-port:
    - DstPort
    - DestinationPort
    - remoteport
  dst-hostname: DstHost
  src-hostname: SrcHost
  src-port:
    - SourcePort
    - localport
  src-ip:
    - sourceip
    - source_ip
    - SourceIP
    - sourceIP
  dst-ip:
    - DestinationIP
    - destinationip
    - destination_ip
    - destinationIP
    - destinationaddress
    - destination
  User:
    - userName
    - EventUserName
  CommandLine: Command
  Protocol: 
    - IPProtocol
    - protocol
  Application:
    - Application
    - application
  SourceHostName:
    - HostCount-source
    - identityHostName
    - sourceAssetName
    - HostCount-src
  DestinationHostname:
    - HostCount-destination
    - Recipient Host
    - DestinationHostName
    - HostCount-dst
  src-packets:
    - PacketRatio-src
    - src-packets
  dst-packets:
    - PacketRatio-dst
    - dst-packets
  src-bytes: src-bytes
  dst-bytes: dst-bytes
  ExternalSeverity:
    - External Severity
    - Observeit Severity
  SourceMAC:
    - SourceMAC
    - MAC
    - sourceMAC
  DestinationMAC: DestinationMAC
  SourceOS:
    - SourceOS
    - OS
  DestinationOS: DestinationOS
  TargetUserName: DestinationUserName
  SourceUserName: SourceUserName
  url_category: XForceCategoryByURL
  EventSeverity: EventSeverity
  Source:
    - Source
    - source