platform: Palo Alto Cortex XSIAM
source: windows_application

default_log_source:
  preset: xdr_event_log

field_mapping:
  EventID: action_evtlog_event_id
  Provider_Name: provider_name

raw_log_fields:
  src_ip: regex
  source: regex
  additional_information: regex
  EventData: regex
  Channel: regex
  statement: regex
  Faulting application path: regex
  object_name: regex
  class_type: regex
  action_id: regex
  Data: regex
  Message: regex
  Level: regex
